pullPolicy: "IfNotPresent"
ingressIP: "" # defined during helm install

couchdbUrl: "http://couchdb-svc-couchdb.couch:5984"

#tls:
#  - hosts:
#      - example.com
#    refName: tls-example-com

images:
  freehealth:
    repository: "docker.taktik.be/freehealth-connector"
    tag: "" # helm install
    replicaCount: 3
    javaOpts: # config
    memoryRequest: "2300Mi"
    memoryLimit: "2300Mi"
    cpuRequest: 50m
    cpuLimit: 2
    servicePort: 8090
    debug: true
    env: {}